# Generated by Django 3.0 on 2024-02-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0007_auto_20240225_0740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profiledata',
            unique_together={('company_name', 'phone_number')},
        ),
    ]
